source 'https://rubygems.org'

ruby '2.3.3'

gem 'rails', '4.2.5.1'
gem 'sqlite3'
gem 'spring', group: :development
gem 'raddocs', :github => "smartlogic/raddocs"

group :test, :development do
  gem 'rspec-rails'
  gem 'rspec_api_documentation', :path => "../"
end
