source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'
gem 'inherited_resources'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  gem 'json_spec'
end

group :test, :development do
  gem 'rspec-rails'
  gem 'rspec_api_documentation', :path => "../"
  gem 'raddocs', :github => "smartlogic/raddocs"
end
